name: Export Godot Project

on:
  push:
    branches:
      - master

env:
  GODOT_VERSION: "4.4.1-stable"
jobs:
  import-assets:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.1
    steps:
      - uses: actions/checkout@v4
      - name: Cache import assets
        uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: Import assets
        run: godot --headless --verbose --editor --quit

  export:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Aseprite cache
        uses: actions/cache/restore@v4
        id: aseprite-cache
        with:
          path: "aseprite/build/bin"
          key: aseprite-bin

      - name: Checkout Aseprite
        uses: actions/checkout@v5
        if: steps.aseprite-cache.outputs.cache-hit != 'true'
        with:
          path: aseprite
          repository: "aseprite/aseprite"
          submodules: recursive

      - name: Install Aseprite Dependencies
        shell: bash
        working-directory: aseprite
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            libpixman-1-dev libfreetype6-dev libharfbuzz-dev zlib1g-dev \
            libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev

      - name: Aseprite ccache
        uses: hendrikmuhs/ccache-action@v1.2.17
        if: steps.aseprite-cache.outputs.cache-hit != 'true'
        with:
          key: aseprite-ccache

      - uses: aseprite/get-ninja@main
        if: steps.aseprite-cache.outputs.cache-hit != 'true'

      - name: Generate Aseprite Makefiles
        if: steps.aseprite-cache.outputs.cache-hit != 'true'
        shell: bash
        working-directory: aseprite
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DENABLE_TESTS=OFF \
            -DENABLE_SCRIPTING=off \
            -DENABLE_CCACHE=on \
            -DLAF_BACKEND=none

      - name: Compile Aseprite
        if: steps.aseprite-cache.outputs.cache-hit != 'true'
        shell: bash
        working-directory: aseprite/build
        run: ninja

      - name: Save Aseprite cache
        uses: actions/cache/save@v4
        with:
          path: "aseprite/build/bin"
          key: aseprite-bin

      - name: Add Aseprite to PATH
        shell: bash
        run: echo "$PWD/aseprite/build/bin" >> $GITHUB_PATH

      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          path: hooked

      - name: (debug) aseprite
        run: |
          echo $PATH
          ls -l $PWD/aseprite/build/bin
          aseprite --version
          aseprite --all-layers -b --list-layers ./hooked/art/player.aseprite
          aseprite --all-layers -b --list-tags --list-slices --data /tmp/player.json --format json-array --sheet /tmp/player.png ./hooked/art/player.aseprite --merge-duplicates --sheet-type packed --shape-padding 0
          ls /tmp/player.*

      - name: Export game using Godot
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}_linux.x86_64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}_export_templates.tpz"
          relative_project_path: "./hooked"
          use_preset_export_path: true
          cache: true

      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: ./hooked/export/Hooked-linux.zip
          if-no-files-found: error

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: ./hooked/export/Hooked-windows.zip
          if-no-files-found: error

      - name: Upload MacOS
        uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: ./hooked/export/Hooked-macOS.zip
          if-no-files-found: error
